name: helloworld app docker build
on: [push]
jobs:
  Check-and-build-helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Hello Worlding
        run: |
          docker build -t  helloworld-app . 
      - name: Publish to Azure Container Registry
        uses: Azure/docker-login@v1
        with:
          login-server: ue19containers.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: docker push helloworld-app
