name: helloworld app docker build
on: [push]
jobs:
  Check-and-build-helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Hello Worlding
        run: |
          docker build -t  helloworld-app . 
